log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  endpoint: "http://localhost:3001"
  username: "user-issuer"
  password: "password-issuer"

network:
  rpc_url: http://127.0.0.1:8545/
  private_key: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 # without 0x
  gas_limit: 30000000
  chain_id: 31337

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: polygonid-integration-svc
  service_port: 80
