log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  endpoint: "http://localhost:3001"
  username: "user-issuer"
  password: "password-issuer"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: polygonid-integration-svc
  service_port: 80
