openapi: 3.0.0
info:
  version: 1.0.0
  title: polygonid-integration-svc
  description: TokenE Module for integration with Polygon ID issuer
servers:
  - url: 'https://api.demo.polygonid.issuer.integration.com'
    description: TokenE Module for integration with Polygon ID issuer
